language: generic
sudo: required
os: linux

services:
  - docker

notifications:
  email:
    - "info@valentineus.link"

jobs:
  include:
    - stage: test
      env:
        - "IMAGE=./default/1.6"
        - "IMAGE=./default/1.5"
        - "IMAGE=./default/1.4"
        - "IMAGE=./build/1.6"
        - "IMAGE=./build/1.5"
        - "IMAGE=./build/1.4"
      script:
        - docker build --tag "${TRAVIS_REPO_SLUG}" "${IMAGE}"
    - stage: deploy
      deploy:
        provider: script
        script:
          - "curl -H 'Content-Type: application/json' --data '{\"build\":true}' -X POST 'https://registry.hub.docker.com/u/valentineus/meteor/trigger/${TOKEN}/'"