language: generic
sudo: required
os: linux

services:
  - docker

notifications:
  email:
    - "info@valentineus.link"

env:
  - TAG="latest"    RELEASE="latest"  DIRECTORY="./default/latest"
  - TAG="1.7"       RELEASE="1.7"     DIRECTORY="./default/release"
  - TAG="1.6"       RELEASE="1.6"     DIRECTORY="./default/release"
  - TAG="1.5"       RELEASE="1.5"     DIRECTORY="./default/release"
  - TAG="1.4"       RELEASE="1.4"     DIRECTORY="./default/release"
  - TAG="build"     RELEASE="latest"  DIRECTORY="./build/latest"
  - TAG="build-1.7" RELEASE="1.7"     DIRECTORY="./build/release"
  - TAG="build-1.6" RELEASE="1.6"     DIRECTORY="./build/release"
  - TAG="build-1.5" RELEASE="1.5"     DIRECTORY="./build/release"
  - TAG="build-1.4" RELEASE="1.4"     DIRECTORY="./build/release"

script:
  - docker build --build-arg RELEASE="${RELEASE}" --tag "${TAG}" "${DIRECTORY}"

after_success:
  - "curl -H 'Content-Type: application/json' --data '{\"docker_tag\":\"${TAG}\"}' -X POST 'https://registry.hub.docker.com/u/valentineus/meteor/trigger/${TOKEN}/'"
