language: generic
sudo: required
os: linux

services:
  - docker

notifications:
  email:
    - "info@valentineus.link"

env:
  - "IMAGE=./default/latest"
  - "IMAGE=./default/1.7"
  - "IMAGE=./default/1.6"
  - "IMAGE=./default/1.5"
  - "IMAGE=./default/1.4"
  - "IMAGE=./build/latest"
  - "IMAGE=./build/1.7"
  - "IMAGE=./build/1.6"
  - "IMAGE=./build/1.5"
  - "IMAGE=./build/1.4"

script:
  - docker build --tag "${TRAVIS_REPO_SLUG}" "${IMAGE}"

jobs:
  include:
    - stage: deploy
      deploy:
        provider: script
        script:
          - "curl -H 'Content-Type: application/json' --data '{\"build\":true}' -X POST 'https://registry.hub.docker.com/u/valentineus/meteor/trigger/${TOKEN}/'"